// Generated by GraphWalker (http://www.graphwalker.org)
package es.udc.pa.pa002.practicapa.testautomation;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "es/udc/pa/pa002/practicapa/testautomation/Estados.graphml")
public interface Estados {

    @Vertex()
    void Eliminado();

    @Edge()
    void find();

    @Edge()
    void save();

    @Vertex()
    void Creado();

    @Edge()
    void saveOrUpdate();

    @Edge()
    void remove();
}
